{% set name = "verr" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/verr-{{ version }}.tar.gz
  sha256: 7bb5547bbc53284cd895a0d03d231566b584ec3611ef46541040b45b06994ef1

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - verr
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Amourspirit/python-version-num
  summary: Represents a version number that can be parsed and compared.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Amourspirit
